# Site settings
title: "Black Women in Digital Fabrication-Craft Fund Research Grant 2025"
description: "Who are the Black women and young girls forging our digitally handmade future, who are their instructors and how do we continue to leverage the craft through textiles?"
domain: bw-in-digi-fab-research.github.io   
baseurl: /bw-in-digi-fab-research/ # The subpath of your site (e.g., /blog), leave blank for root.
url: "https://erikkaincolor.github.io/bw-in-digi-fab-research" # Your site's URL.

# Build settings
markdown: kramdown
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

# Other settings
paginate: 10 # Number of posts per page
paginate_path: "/page:num/"
